name: Salesforce Multi-Branch CI/CD Pipeline

on: 
  push:
      branches:
          - main
          - dev
          - feature/**

  pull_request:
      branches:
        - dev
        - main
env:
  TEST_COVERAGE_THRESHOLD: 75

jobs:
    validate-branch:
        name: Validate Branch in Scratch Org
        runs-on: ubuntu-latest
        if: github.ref  !=  'refs/heads/main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Salesforce CLI & PMD
              run: |
                npm install @salesforce/cli --global
                curl -LJO https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
                unzip pmd-bin-6.55.0.zip -d pmd
                export PATH=$PATH:$(pwd)/pmd/pmd-bin-6.55.0/bin
            
            - name: Authenticate Salesforce Org
              run: |
                echo "${{ secrets.SF_AUTH_URL }}" > authfile.txt
                sf org login sfdx-url --sfdx-url-file authfile.txt --alias Prod --set-default

            - name: Create Scratch Org
              run:  |
                sf org create scratch --definition-file config/project-scratch-def.json --alias ScratchOrg --set-default --duration-days 1

            - name: Push Source to Scratch Org
              run: sf project deploy start --target-org ScratchOrg

            - name: Run Apex Tests
              run:  |
                sf apex run test --target-org ScratchOrg --code-coverage --result-format json --output-dir test-results
                COVERAGE=$(jq '.result.summary.codeCoverage.coverage' test-results/test-result.json)
                echo "Test Coverage: $COVERAGE%"
                if (( $(echo  "$COVERAGE  < $TEST_COVERAGE_THRESHOLD" | bc  -l) )); then
                  echo  "Code coverage  ($COVERAGE%)  is below threshold ($TEST_COVERAGE_THRESHOLD%)"
                  exit 1
                else
                  echo  "Code coverage meets threshold."
                fi

            - name: Run PMD Analysis
              run: |
                pmd/bin/run.sh pmd -d force-app/main/default/classes -R apex-apexunit -f text

            - name: Delete Scratch Org
              run: sf org delete scratch --target-org ScratchOrg --no-prompt
            
    deploy-prod:
      name: Deploy to Production
      runs-on:  ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Install Salesforce CLI 
            run: |
              npm install @salesforce/cli --global
              sf --version
            
          - name: Authenticate Production Org
            run: |
              echo "${{ secrets.SF_AUTH_URL }}" > authfile.txt
              sf org login sfdx-url --sfdx-url-file authfile.txt --alias Prod
            
          - name: Deploy Metadata to Production
            run: sf project deploy start --target-org Prod



              